# Generated by Django 3.2.6 on 2021-09-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lprApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='device',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
