# Generated by Django 3.2.6 on 2021-09-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lprApp', '0002_video_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='device',
        ),
        migrations.AddField(
            model_name='videosession',
            name='device',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
